/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Clave",                                           "pl": "Hasło",                                           "zh-cn": "密码"},
    "Port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "Порт",                                            "pt": "Porta",                                           "nl": "Haven",                                           "fr": "Port",                                            "it": "Porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "港口"},
    "Server adress": {                               "en": "Server adress",                                   "de": "Serveradresse",                                   "ru": "Адрес сервера",                                   "pt": "Endereço do servidor",                            "nl": "Server adres",                                    "fr": "L'adresse du serveur",                            "it": "Indirizzo del server",                            "es": "Dirección de servidor",                           "pl": "Adres serwera",                                   "zh-cn": "服务器地址"},
    "Update": {                                      "en": "Update",                                          "de": "Aktualisieren",                                   "ru": "Обновлять",                                       "pt": "Atualizar",                                       "nl": "Bijwerken",                                       "fr": "Mettre à jour",                                   "it": "Aggiornare",                                      "es": "Actualizar",                                      "pl": "Aktualizacja",                                    "zh-cn": "更新"},
    "Update interval": {                             "en": "Update interval",                                 "de": "Updateintervall",                                 "ru": "Интервал обновления",                             "pt": "Intervalo de atualização",                        "nl": "Bijwerkingsonderbreking",                         "fr": "Intervalle de mise à jour",                       "it": "Intervallo di aggiornamento",                     "es": "Intervalo de actualización",                      "pl": "Interwał aktualizacji",                           "zh-cn": "更新间隔"},
    "Username": {                                    "en": "Username",                                        "de": "Nutzername",                                      "ru": "Имя пользователя",                                "pt": "Nome do usuário",                                 "nl": "gebruikersnaam",                                  "fr": "Nom d'utilisateur",                               "it": "Nome utente",                                     "es": "Nombre de usuario",                               "pl": "Nazwa użytkownika",                               "zh-cn": "用户名"},
};